language: python

env:
    global:
      - PSQL_USERNAME=erick_gandarilla
      - PSQL_PASS=pass
      - PSQL_DBNAME=prueba
      - PSQL_HOST=104.237.129.63
      - PSQL_PORT=5506

services:
    - postgresql
install:
    - pip install django django-location-field djangorestframework djangorestframework-simplejwt PyJWT django-cors-headers psycopg2-binary
before_script:
  - psql -c "CREATE DATABASE prueba;" -U postgres
  - psql -c "CREATE USER erick_gandarilla WITH PASSWORD pass;" -U postgres
  - psql -c "ALTER USER erick_gandarilla CREATEDB;" -U postgres
  
script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test